In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
dataset = pd.read_csv('data-produksi-benih-ikan-di-provinsi-dki-jakarta-tahun-2019.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(x)

[['Mas' 2019.0 nan]
 ['Nila' 2019.0 4558651.0]
 ['Gurame' 2019.0 227728.0]
 ['Lele' 2019.0 2366170.0]
 ['Kerapu Macan' 2019.0 1541280.0]
 ['Kerapu Hybrid' 2019.0 34500.0]
 ['Kakap Putih' 2019.0 1839120.0]
 ['Bawal Bintang' nan 8400.0]]


In [7]:
print(y)

['Tawar' 'Tawar' 'Tawar' 'Tawar' 'Laut' 'Laut' 'Laut' 'Laut']


In [8]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [9]:
print(x)

[['Mas' 2019.0 8400.0]
 ['Nila' 2019.0 4558651.0]
 ['Gurame' 2019.0 227728.0]
 ['Lele' 2019.0 2366170.0]
 ['Kerapu Macan' 2019.0 1541280.0]
 ['Kerapu Hybrid' 2019.0 34500.0]
 ['Kakap Putih' 2019.0 1839120.0]
 ['Bawal Bintang' 2019.0 8400.0]]


In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [11]:
print(x)

[[0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 2019.0 8400.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 2019.0 4558651.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 2019.0 227728.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 2019.0 2366170.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 2019.0 1541280.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 2019.0 34500.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 2019.0 1839120.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 2019.0 8400.0]]


In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [13]:
print(y)

[1 1 1 1 0 0 0 0]


In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [15]:
print(x_train)

[[0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 2019.0 4558651.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 2019.0 1839120.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 2019.0 8400.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 2019.0 1541280.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 2019.0 2366170.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 2019.0 34500.0]]


In [16]:
print(x_test)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 2019.0 8400.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 2019.0 227728.0]]


In [17]:
print(y_train)

[1 0 1 0 1 0]


In [18]:
print(y_test)

[0 1]


In [33]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [34]:
print(x_train)

[[0.0 0.0 -0.44721359549995787 -0.447213595499958 -0.4472135954999579
  -0.447213595499958 -0.447213595499958 2.23606797749979 0.0
  1.836217428408747]
 [0.0 0.0 2.2360679774997894 -0.447213595499958 -0.4472135954999579
  -0.447213595499958 -0.447213595499958 -0.447213595499958 0.0
  0.07414496537847404]
 [0.0 0.0 -0.44721359549995787 -0.447213595499958 -0.4472135954999579
  -0.447213595499958 2.23606797749979 -0.447213595499958 0.0
  -1.112037982901498]
 [0.0 0.0 -0.44721359549995787 -0.447213595499958 2.23606797749979
  -0.447213595499958 -0.447213595499958 -0.447213595499958 0.0
  -0.11883524421977522]
 [0.0 0.0 -0.44721359549995787 -0.447213595499958 -0.4472135954999579
  2.23606797749979 -0.447213595499958 -0.447213595499958 0.0
  0.4156377785290155]
 [0.0 0.0 -0.44721359549995787 2.23606797749979 -0.4472135954999579
  -0.447213595499958 -0.447213595499958 -0.447213595499958 0.0
  -1.0951269451949632]]


In [35]:
print(x_test)

[[1.0 0.0 -0.44721359549995787 -0.447213595499958 -0.4472135954999579
  -0.447213595499958 -0.447213595499958 -0.447213595499958 0.0
  -1.112037982901498]
 [0.0 1.0 -0.44721359549995787 -0.447213595499958 -0.4472135954999579
  -0.447213595499958 -0.447213595499958 -0.447213595499958 0.0
  -0.9699282481084386]]
